name: Run Cargo Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          cargo test

